name: 'Spellchecker CLI'
description: 'Spellcheck files in your repository.'
inputs:
  files:
    description: "A list of files or globs to spellcheck, separated by spaces."
    required: true
    default: "**/*.txt **/*.md"
  dictionaries:
    description: "A list of files to combine into a personal dictionary, separated by spaces."
    required: false
runs:
  using: "composite"
  steps:
    - run: >
        npx -y spellchecker-cli
          --files ${{ inputs.files }}
          ${{ github.events.inputs.dictionaries != '' && format('--dictionaries {0}', github.events.inputs.dictionaries) || '' }}
      shell: bash
